### ISSUE TITLE
API för att flytta pengar mellan konton

### ISSUE THREAD

**Issue by walle89** [walle89/SwedbankJson#11]
Med personlig kod så kan man flytta pengar mellan egna konton utan krav på verifiering eller uppgradering till en säkrare inloggningsmetod. Med detta skulle man exempelvis göra ett system som bevakar vissa transaktioner som sker oregelbundna och flyttar pengarna automatiskt till/från andra konton.

**Comment by MrNaitX** [comment]
Är det möjligt med SwedbankJson att flytta pengar mellan konton?

**Comment by walle89** [comment]
Swedbank har stöd i sitt API att göra det, men är inte implementerad i SwedbankJson och där av har denna issue todo-taggen.

**Comment by walle89** [comment]
Nu är det möjligt att flytta mellan konton i master trädet. Det som saknas nu är dokumentation och exempelkod. Om inget oförutsett inträffar så kommer den att släppas i nästkommande version. För den som önskar är det bara installera med composer och byta versionsnumret till dev-master

**Comment by walle89** [comment]
Now released in version 0.7.0.
