### ISSUE TITLE
STRONGER_AUTHENTICATION_NEEDED - Den här tjänsten kräver en annan ID-metod. Klicka på Fortsätt för att logga in med ny ID-metod.

### ISSUE THREAD

**Issue by viktorgardart** [walle89/SwedbankJson#17]
Tjabba! 
Håller på att översätta din kod till Objective C, dels för att lära mig språket och dels för att göra en personlig app, så tack för att du släppt detta!

Har fått inloggningen att fungera, och försöker nu att lisa [profillistor](https://github.com/walle89/SwedbankJson/blob/master/src/SwedbankJson.php#L152). Men får tillbaka `STRONGER_AUTHENTICATION_NEEDED`. 
Eftersom inloggningen fungerar så antar jag att mina headers är rätt. Och skickar jag inte med min cookie får jag `AUTHORIZATION_FAILED` vilket är logiskt. 

Vet du något på rakt hand som kan vara fel?

**Comment by walle89** [comment]
Vad roligt att du gör en Objective C implementation av wrappern! Om du lägger upp koden så säg till så länkar jag gärna till den.

Det är svårt att säga vad som kan vara fel utan ha sett hur dina HTTP-requests ser ut. Men det jag kan tänka mig som kan vara galet är du sparar inte de cookies som du får tillbaka vid inloggingen. Använder du en Cookiejar?

Om du gör det eller att en cookiejar det inte löser problemet, då skulle jag behöva HTTP dumpar av dig. Det du behöver göra är att sätta upp en HTTP-proxy som exempelvis Charls proxy ([instruktioner](https://github.com/walle89/SwedbankJson/issues/3#issuecomment-34147371)) eller annan HTTP-proxy som kan hantera SSL. Om du vill bara felsöka mellan din kod och Swedbanks servrar och inte via deras mobilapp så kan du se till att din kod när den gör anropen att den struntar i SSL-certifikatet.

**Comment by viktorgardart** [comment]
Tack så mycket, ska kolla på detta till helgen! 

Lägger självklart upp koden när jag känner mig klar!

**Comment by Muqito** [comment]
Återanvänder du din cookie då?

För skapar du en ny så får du det felmeddelandet.

Jag håller precis på att skapa en uppkoppling i ett annat programmeringsspråk, och där är jag tvungen att koppla uri:n till cookien.

Där använder man baseUri.

Lycka till :)

**Comment by viktorgardart** [comment]
Nu gör jag, jag gjorde inte det tidigare så nu fungerar utmärkt. Tack till er båda!

Har lagt upp koden [här](http://github.com/viktorgardart/SwedbankJson). Just nu sköter jag det inte på det snyggaste sättet men kommer pilla på det under helgen.

**Comment by walle89** [comment]
@viktorgardart Härligt och höra att du har löst det! Om du tycker att din kod är bra nog så lägger jag upp länken till helgen.

@Muqito Nu blev jag nyfiken. Vad för språk skriver du det i? Har du planerat att publicera koden? Ge mig en länk till där du har lagt upp det så kan jag lägga upp den i readme-filen.

**Comment by Muqito** [comment]
@walle89 node.js

Jag funderar på det :)

Kan man påtvinga deras kategorisering på något sätt tror du?

**Comment by walle89** [comment]
@Muqito Vad menar du med "påtvinga deras kategorisering"? Pratar du om utgiftskollen?
