### ISSUE TITLE
Kan ej logga in med företagskonto

### ISSUE THREAD

**Issue by bankshark** [walle89/SwedbankJson#20]
Hej!

Jag lyckas logga in privat med "swedbank", men när jag testar med mitt företagskonto och ställer in applikationen att använda "swedbank_foretag" istället så lyckas den inte logga in. Är detta ett känt problem eller gör jag någonting fel?

Koden jag försöker köra är:
require_once 'vendor/autoload.php';
$auth = new SwedbankJson\Auth\SecurityToken("swedbank_foretag", "personnummer", "engångskod");
$bankConn = new SwedbankJson\SwedbankJson($auth);
$profiles = $bankConn->profileList();

**Comment by walle89** [comment]
Du kan logga in med företagsappen på din Ios- eller Andorid-enhet i vanliga fall? Får du något felmeddelande eller något svar?

**Comment by bankshark** [comment]
Ja, jag kommer in med företagsappen på min android-lur.
Får http 401 och felmeddelande:
{"errorMessages":{"general":[{"code":"LOGIN_FAILED","message":"Det gick inte att logga in. Det kan bero på att du har angett ett felaktigt nummer i fältet för personnummer, att koden som kommer från säkerhetsdosan inte är den förväntade eller att kontrollvärdet är äldre än tre minuter. Vänligen försök igen."}]}}

**Comment by walle89** [comment]
När du loggar in med företagsappen, använder du inloggingsmetoden säkerhetsdosa eller företagskopplad dosa?

**Comment by bankshark** [comment]
Hej, jag använde mig av alternativet säkerhetsdosa.

**Comment by bankshark** [comment]
Du får hojta till om du vill ha hjälp med att debugga detta. Försökte kolla vad appen skickar genom att köra mot en egen proxy, men fick det dessvärre inte att fungera med SSL.

**Comment by walle89** [comment]
Jag gjorde en snabb koll av Swedbank-trafiken, men vad jag kan se så hittar jag inget som skiljer mellan företagsappen och den för privatkunder. Jag har även provat att göra motsvarande i wrappern och jag kommer åtminstone till steget där meddelandet "Du saknar avtal för Mobilbanken Företag." dyker upp, vilket är samma som i företagsappen. Fyller jag i felaktig inloggning så kan jag återskapa samma meddelande. Då provade jag inloggning med både personlig kod och säkerhetsdosa med engångskod.

När jag avlyssnar SSL-trafik så använder jag [Charles Proxy](http://www.charlesproxy.com/) som kan användas gratis i 30 dagar. Du kan följa [denna guide](http://jaanus.com/blog/2012/02/12/debugging-http-on-an-android-phone-or-tablet-with-charles-proxy-for-fun-and-profit/) för att komma igång med SSL-avlyssningen på Andorid. Tyvärr är guiden lite utdaterad då Charles Proxy har nyligen börjat med att generera root-certifikatet som guiden ovan inte tar upp. Men i övrigt är det inga större överraskningar.

När du har fått igång Chalres Proxy och vill skicka mig hur din trafik ser ut så följ [denna instruktion] (https://github.com/walle89/SwedbankJson/issues/3#issuecomment-34170931).
