### ISSUE TITLE
Stavfel?

### ISSUE THREAD

**Issue by steenstn** [walle89/SwedbankJson#22]
Jag funderar på att använda mig av den här koden inom en snar framtid så jag satt och tittade i den och hittade vad som ser ut som ett stavfel
challenge -> challange
https://github.com/walle89/SwedbankJson/blob/master/src/Auth/SecurityToken.php#L67

**Comment by walle89** [comment]
Ja det verkar så. Men jag tar en närmare titt på det ikväll.
