### ISSUE TITLE
Kan inte hitta klassen SwedbankJson\Auth\PersonalCode

### ISSUE THREAD

**Issue by edgren** [walle89/SwedbankJson#23]
Tjo!

Jag använder din klass för första gången nu och jag har problem med att hitta två av de viktigaste klasserna; SwedbankJson\Auth\SecurityToken och SwedbankJson\Auth\PersonalCode. Jag har skrivit såhär i index.php, som ligger bland de andra filerna, till exempel LICENSE; README.md och så vidare:

    <?php
    require_once 'src/SwedbankJson.php';

    // Inställningar
    define('BANK_APP',  'swedbank');     // Byt mot motsvarande IOS/Android mobil app. Alternativ: swedbank, sparbanken, swedbank_foretag, sparbanken_foretag, swedbank_ung, sparbanken_ung
    define('USERNAME',  198903060000);   // Person- eller organisationsnummer
    define('PASSWORD',  'fakePW');       // Personlig kod

    $auth = new SwedbankJson\Auth\SecurityToken(BANK_APP, USERNAME, $challengeResponse);
    $bankConn = new SwedbankJson\SwedbankJson($auth);
    ?>

**Comment by walle89** [comment]
Vänligen läs och följ [insllationsinstruktionerna](https://github.com/walle89/SwedbankJson#installation) samt använd exempelkoden. Att använda min wrapper utan Composer är inte att rekommendera. Har du frågor kring Composer kan du läsa om det [här](https://github.com/walle89/SwedbankJson/issues/7).
