### ISSUE TITLE
Frågor kring swedbank's API

### ISSUE THREAD

**Issue by lasdjfk** [walle89/SwedbankJson#25]
På de transaktioner som har **expenseControlIncluded** får man även ett **id** vilket är trevligt för blir mycket enklare att synka transaktionerna mot en egen databas då. Men transaktionerna verkar inte få detta förrän efter ett par dagar. När man loggar in via appen står det för dessa transaktioner "denna transaktion kommer att kategoriseras inom kort". Hur kan detta komma sig?

**Comment by walle89** [comment]
Nja, alla ID:n (vad jag vet) som förekommer i API:et är unika per session. Du kan alltså inte använda dem för att kolla om en tidigare transaktion redan finns inne. ID-nummer används till att kunna göra ändringar kopplat till utgiftskollen (ex byta kategori).

Det sätt som jag löst det på är att helt enkelt spara så mycket information om transaktionen som möjligt (åtminstone datum, beskrivning, summa och valuta ) och jämföra det mot databasen.

**Comment by lasdjfk** [comment]
Ah tack, men vad synd. Ja då får man väl hitta på något sådant. Skulle kunna ladda 10 st överlappande transaktioner som redan finns i databasen innan den lägger till nya för att kontrollera att inte någon missas eller dubbelregistreras. Kan ju finnas trans. som har samma datum, beskrivning och summa (om man t.ex. köper flera öl en kväll på krogen).
