### ISSUE TITLE
Hur använda koden?

### ISSUE THREAD

**Issue by edgren** [walle89/SwedbankJson#26]
Hej!

Jag har laddat hem alla filer och lagt in en index.php i src-katalogen. Efter det skrev jag in mitt personnummer i textfältet och tryckte sen på knappen. Då får jag följande felmeddelande:

`Fatal error: Class 'SwedbankJson\Auth\SecurityToken' not found in ...\SwedbankJson-master\src\index.php on line 21`

Vad göra nu?

**Comment by walle89** [comment]
Var vänligen läs [README.md](https://github.com/walle89/SwedbankJson/blob/master/README.md) och [introduktion.md](https://github.com/walle89/SwedbankJson/blob/master/docs/introduktion.md) då dem innehåller all information du behöver för att komma igång. Du måste använda sig av Composer för att kunna installera, vilket jag tidigare förklarat för dig i issue #23.

Har du frågor angående om instruktionerna så ställ dem i denna issue.
