### ISSUE TITLE
Frågor om API:et

### ISSUE THREAD

**Issue by Carlgo11** [walle89/SwedbankJson#29]
Hej!
Hittade ditt repository för några veckor sedan. Är jättekul att någon har tagit sig tiden att dokumentera allt det här!

Har några frågor kring API:et som jag inte hittat svar på i dina [docs](https://github.com/walle89/SwedbankJson/tree/master/docs) filer.

1. Vad är AccountID? Är det samma som `[id] => 29baec9d3f2a478866FAKEebb5d3948ee4c4c9d3` för
[![screenshot](https://puu.sh/s34Tx/a4d27a7195.png)](http://puu.sh/s34Tx/a4d27a7195.png)
Testade nämligen att använda mitt egna ID taget från accountDetails() men då får jag bara ett ` Uncaught SwedbankJson\Exception\ApiException: general (1): IDENTITY_MISSING - Kunde inte hitta kontot. in /var/www/html/swedbank/vendor/walle89/swedbank-json/src/Auth/AbstractAuth.php:306` error-meddelande.
Har också testat att använda mitt accountQuickBalanceSubID  men det funkade inte heller.

2. Vad betyder `[priority]` taggen?

Det är alla mina frågor (för tillfället 😉)

Tack!
//@Carlgo11

**Comment by walle89** [comment]
Tack! Jag gillar twofactorauth.org :)

1. AccountID är ett ID som är unikt per session som används för att referera till ett konto för ett visst action (ex. lista transaktioner). 

Angående IDENTITY_MISSING, det låter som att du har matat in ett NULL-värde. Har du provat exemplet [selecting-specific-account](https://github.com/walle89/SwedbankJson/blob/master/INSTALL.md#selecting-specific-account)?

2. Det vet jag inte. Jag tror det är något som är bara kopplat till appen.

**Comment by Carlgo11** [comment]
Tack! Jag fixade det med hjälp av länken du skickade mig.
Ny fråga, hur kan folk födda på 2000-talet använda API:et? Ser ut som att koden bara tillåter 10 siffror för personnummer och att kodens default århundrade är 1900-talet.
