### ISSUE TITLE
Begränsning i antalet transactions i accountDetails()

### ISSUE THREAD

**Issue by jarnheimer** [walle89/SwedbankJson#31]
Jag har problem med funktionen `accountDetails()` som maximalt kan ge 114 transaktioner. Även om vi använder paging. 

## Exempelvis

```
$transactionsPerPage = 100; 
$page = 1;
accountDetails($accountID, $transactionsPerPage, $page);
```
ger **100 rader**.

```
$transactionsPerPage = 100; 
$page = 2;
accountDetails($accountID, $transactionsPerPage, $page);
```
ger **14 rader** även om fler finns.

Är det något som vet om detta fel ligger på SwedbankJson, Swedbank eller vårt konto?

**Comment by walle89** [comment]
Den begräsning som jag känner till är att Swedbank sparar transaktioner max 13 månader båkåt i tiden. SwedbankJson lägger sig inte i outputen som kommer ut från API:et, utan spottar ut den som den är.

Jag kan göra ett litet test lite senare idag och se hur många rader som jag får ut och hur långt bakåt i tiden dessa sträcker sig.

**Comment by jarnheimer** [comment]
> Den begräsning som jag känner till är att Swedbank sparar transaktioner max 13 månader båkåt i tiden. SwedbankJson lägger sig inte i outputen som kommer ut från API:et, utan spottar ut den som den är.
> 
> Jag kan göra ett litet test lite senare idag och se hur många rader som jag får ut och hur långt bakåt i tiden dessa sträcker sig.

Intressant och STORT TACK @walle89 ! I vårt case är det transaktioner där den äldsta inte är mer än några dygn.

**Comment by walle89** [comment]
@jarnheimer NP. Just nu är jag på jobbet och kommer nog bara hinna med att titta på det när jag kommer hem. Men det du skulle kunna göra under tiden är att kolla i någon av Swedbanks mobilappar och se om samma sak händer där.

**Comment by jarnheimer** [comment]
Det stämmer @walle89 . Samma begränsning finns i Swedbanks företagsapp. Efter drygt 100 transaktioner går det inte att hämta fler.

**Comment by walle89** [comment]
Humm... har du i andra sammanhang lyckas få fram resten av transaktionerna?

Eventuellt skulle du kunna testa [nya Internetbanken](https://online.swedbank.se/app/privat/?ns=1), för den använder en annan version av API:et. Den är egentligen till för privatpersoner, men det kanske kan gå.

Annars använder SwedbankJson samma API som företagsappen, och då bör begränsningen rimligen ligga hos Swedbank (ska försöka verifiera detta sen). Om så är fallet så kan jag inget göra, utan i så fall behöver du ta kontakt med Swedbank och kolla varför.

**Comment by walle89** [comment]
Jag gjorde ett test nu med följande script för ett privatkonto:

```php
$count = 0;
$perPage = 50;
for($i=0; true; $i++){
    $statements = $bankConn->accountDetails('*my-account-ID*', $perPage, $i);

    $count += $statements->numberOfTransactions;

    if($statements->numberOfTransactions < $perPage){
        break;
    }
}
print_r(end($statements->transactions));
echo $count;

$bankConn->terminate();
```
Resultat: 1000+ transaktioner med sistadatum 2015-10-15 (~18 månader).

Med andra ord så verkar det vara något hos Swedbank som är lurt, då jag inte kan komma på något annat som skulle kunna förklara det. Kanske möjligtvis att den typ av konto du hämtar från har egna speciella begränsningar.

Hur som helst så behöver du kanske kontakta Swedbank och se till att dem fixar det. Se bara till att du partar i kontexten av mobilapparna. Jag har en känsla av att de vill hellre supporta sina appar än detta projekt. ;) 

Om du hittar en lösning så dela gärna med dig av den. Jag är mycket nyfiken på vad det kan vara för något. =) 

Fotnot: Intressant att man ändå kan få ut 18 månader, med tanke på att Swedbank själva säger man [bara kan få ut 13](https://hjalp.swedbank.se/sidhjalp-internetbanken-privat/ekonomisk-oversikt/konton-och-lan-oversikt/visa-kontohistorik/).

**Comment by jarnheimer** [comment]
Stort tack @walle89 !

Jag ska kontakta dem. Och mycket riktigt verkar de behandla Swedbank Företag annorlunda än Privat. Jag återkommer när jag fått svar från dem!
