### ISSUE TITLE
Att få användarens personliga uppgifter och visa deras konto 

### ISSUE THREAD

**Issue by oehqoehfo** [walle89/SwedbankJson#35]
Ursäkta med mitt språk(jag är en invandrare)
Hej tack för ditt jättekul kod
Vår grupp har en uppgift att koda en prototyp Open banking. ag kan koda Javascript och JSON ganska bra men jag är inte PHP kunnig kille...  (Jag kan koda PHP men lite lite lite). 

Jag har läst ditt kod och prövat alla 3 swedbank account API:erna(som fungerade jättebra). Jag redan har gjort en nästan färdig kod(bara ändra lite eller lägga till )

Men den störst och viktigast problem är hur servern eller API ska förstå vem är användaren? Till exempel om jag mattar in mina personliga uppgifter, då webben ska visa mitt konto med saldo, inte ditt. 

Kan ni ge lite tip eller små exempel med beskrivningen hur ska jag koda för att lösa problemet?

**Comment by walle89** [comment]
Hej,

Jätteroligt att du har kommit igång och testat koden!

Vilken kurs går du? Är det på gymnasium eller universitet/högskola? Kan du berätta mer om er uppgift? Detta projekt använder inte Swedbank Open Banking. Du bör fråga din lärare först om det är okej att ni använder detta bibliotek.

Som svar på din fråga så vet API:et vilken användare det är genom att du matar in personnumret för användaren. Sedan måste användaren logga in och det kan man göra genom exempelvis BankID. Om du vill att jag ska kunna använda använda din kod för att logga in och se mitt konto och saldo, så behöver jag skriva in mitt personnummer och göra en inloggning.

Det går inte se någon annans persons saldo utan att den personen loggar in på kontot. Det skulle vara jättedåligt att alla kan se mitt saldo på mitt konto utan krav på inloggning. ;)

Jag hjälper dig gärna med kodexempel, men jag förstår inte helt vad exakt du vill göra.

If you want to, you can ask your questions in English if that is easier for you. :)

**Comment by oehqoehfo** [comment]
Tack för trevlig svar!
Jag går gymnasiet fjärdeårs kurs (T4). Fick en uppgift att koda en prototyp open banking.
Namnet på github projekt är SwedbankJSON därför tänkte jag den kod använder Swedbank Open Banking API

Programmet ska fungera så:
1. Användaren ska mata in hans bank och personnmmer
2. Bank som han har valt ska undersöka om finns något konto som matchas med personnummer.
3.Visa konto om finns 
BankID eller liknande jag tror vi ska inte använda dem eftersom vi ska göra bara prototyp.
Jag kan skicka personnummer från webben till Server. Det är ingen problem 
Men hur ska jag göra för att bankservern kunde hämta numret och visa relaterat konto? 

Ursäkta med språket 
Tack för hjälp:)

**Comment by walle89** [comment]
Jag förstår förvirringen, men detta projekt skapades 2013 och Swedbank Open Banking är nytt och är knappt 1 månad gammal. Det är knappt någon som har hunnit skriva och publicerat kod för den. En anledning till detta är att Swedbank Open Banking enbart finns som sandbox än så länge. Den innehåller ingen riktig data och vad jag förstår så har de inte implementerat någon system för inloggning. Det är därför den passar bra till att bygga och testa prototyper med. 

Detta projekt använder sig av riktig data, med riktiga personnummer, riktiga konton och med riktiga pengar. Därför är den inte lika lämpligt att testa och bygga prototyper med. Sedan måste BankID eller säkerhetsdosa användas för att använda detta API. Med tanke på detta och det inte är Swedbank Open Banking så är jag lite tveksam till om din lärare skulle godkänna dig om du använder min kod. Så det är nog bäst att fråga din lärare om det är okej att använda min kod för din lösning.

Om din lärare säger det är okej så hjälper jag dig. Jag kan hjälpa med hur du kan använda min kod. Dock inte med Open Banking då jag inte är så bra på det ännu (jag är också Swedbank Open Banking nybörjare ;P)
