### ISSUE TITLE
create subscription ID's for connected accounts

### ISSUE THREAD

**Issue by nonbinary** [walle89/SwedbankJson#36]
Hi!

I'm trying to see if I can get this application to work in its current form. Not sure if v4 of the API is still usable?

Anyway: I'm trying to get a subscription ID for an account that is owned by an organization. The account is not listed in the quickbalance/accounts data for the person with access to the account. I'm guessing it's only listing accounts owned by the person.

**Comment by walle89** [comment]
I guess you need to select a different profile (https://github.com/walle89/SwedbankJson/blob/master/INSTALL.md#profile-selector). How I designed this API client is that default it's going to select the personal account. 

With that said, I'm not sure if quickbalance does exists for the cooperate version of the app (I have no access to it). If does exists for either ios/andorid app "Swedbank företag" or "Sparbankerna företag", you should be able to find it.

**Comment by nonbinary** [comment]
Looks like you're right. Using corporate profiles, I was able to see connected ID's, but nothing is listed under quickBalanceAccounts() using the corporate profiles. I guess it's not an avaliable feature. I can't see it in the android företag-app either.
I'm wondering if their new OpenBanking API can be used to do this...

**Comment by walle89** [comment]
In order to use the OpenBanking API from Swedbank you need an AISP license. In Sweden you need to apply such license at [Finansinspektionen](https://www.fi.se/sv/bank/andra-betaltjanstdirektivet-psd-2/). There is one fee to apply and another yearly inspection fee (minimum 10 000 SEK) from what I have found out. In other words, it's quite expensive (at least to an individual).

Can share the use case of why you want to use quick balance? I maybe can help you to find a way to access the information you want.

**Comment by nonbinary** [comment]
Yeah, it looks like OpenBanking isn't usable to us. I do, however, wonder if it'd be possible to set up an organization that can use this API, and let private users use that. Something to make this API avaliable for open-source banking apps.
But that's a different project.

Atm we'll use your API, and pull the info once per day, and the person with the BankID will authorize access for the application.

The use case is this:
We're setting up a donation campaign, and want to keep track of how much money we've gotten. The donations come in from multiple sources (bankgiro, autogiro, swish). The easiest way to keep the information up-to-date is, for us, to pull the bank balance, and then add any withdrawal amounts to that.
We'll then present this info on a webpage. We decided to pull this info once per day. We were kind of hoping to do it hourly, or on every page load, but that doesn't seem possible. At least not safely.

**Comment by walle89** [comment]
> Yeah, it looks like OpenBanking isn't usable to us. I do, however, wonder if it'd be possible to set up an organization that can use this API, and let private users use that. Something to make this API avaliable for open-source banking apps.
> But that's a different project.
I have read about a similar idea at this [forum post about Bankdroid 2.0](https://swedroid.se/forum/threads/bankdroid-2-0-baserad-pa-open-banking-psd2.166077/). It should be possible and unless the banks wants to provide this kind of service, I guess this is the only solution to get access to the OpenBanking APIs.

> Atm we'll use your API, and pull the info once per day, and the person with the BankID will authorize access for the application.
> 
> The use case is this:
> We're setting up a donation campaign, and want to keep track of how much money we've gotten. The donations come in from multiple sources (bankgiro, autogiro, swish). The easiest way to keep the information up-to-date is, for us, to pull the bank balance, and then add any withdrawal amounts to that.
> We'll then present this info on a webpage. We decided to pull this info once per day. We were kind of hoping to do it hourly, or on every page load, but that doesn't seem possible. At least not safely.

Well yes, in your case I think this is the way to go if you just want to have one API with updated status.  

If you want to automate this I would suggest look into if you can use the [Swish Merchant API](https://developer.getswish.se/merchants/). I know Bankgirocentralen have ways to automatically send transactions files for bankgiro accounts, at least on a daily basis, but you need to contact them for more details.

**Comment by nonbinary** [comment]
We've been looking into automatically sending files for autogiro, we're using [byrokrat's giroapp](https://github.com/byrokrat/giroapp). Sadly, for autogiro at least, they have ridicilous fees to give automated access. They don't state it on their webpages, but simple certificate-authenticated access costs from something like €1000 per month. I'm guessing the main bankgiro have similar prices.

Interesting thread with Bankdroid, will keep my eyes on that! I might look into getting some community-based access to this, there should be enough people interested in it...
