### ISSUE TITLE
memory size exhausted

### ISSUE THREAD

**Issue by NisseDILLIGAF** [walle89/SwedbankJson#37]
Tjena...
Det sluta fungera hos mig för några veckor sedan, har inte haft tid att kolla på det förrän nu..
jag får detta felmeddelandet när jag kör koden...
vet inte riktigt var, men försök att kontakta banken och meddelandet kommer upp.

> PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) in /var/www/html/swedb/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113

Har gjort en nyinstallation på en annan rPi jag har .. och samma sak där...
Är det någon annan som har samma problem, eller är det bara hos mig?

Känns lite 'naket' att inte ha full koll och få meddelanden efter varje sak som händer på mitt konto :)

edit.
jag försökte med `ini_set('memory_limit', '-1');`
då fick jag...
 

> PHP Fatal error:  Out of memory (allocated 681574400) (tried to allocate 53248 bytes) in /var/www/html/swedb/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113

**Comment by walle89** [comment]
Jag har gjort några snabbtester nu och det verkar som att Swedbank har gjort någon ändring i sitt API. Exakt vad vet jag inte ännu, utan jag får nog kika på det närmare antingen ikväll eller till helgen.

**Comment by NisseDILLIGAF** [comment]
Tack för snabbt svar...
Ta den tid du behöver/kan...
tyvärr har jag inte mycket tid själv, men är det något du behöver från mig så säg bara till!

**Comment by CirruZZ** [comment]
Råkar ut för samma sak...

Nedan är från inloggningsförsök med BankID
```
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /volume1/web/ynab/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /volume1/web/ynab/vendor/guzzlehttp/promises/src/TaskQueue.php on line 24
```

**Comment by walle89** [comment]
Om ni uppdaterar till version 0.7.2 så ska det nu vara fixat.

Problemet var att Swedbank har uppdaterat minimum versionskravet för deras Swedbank app och deras API svara med "Du måste uppgradera din app". Detta kunde inte klienten hantera och ledde till en evighets lång utloggnings loop och därmed fyllde minnet.

Uppdatering till version 0.7.2 bör vara bakåtkompatibelt med de flesta tidigare versioner.

**Comment by NisseDILLIGAF** [comment]
tack för snabb felsökning!
har du uppdaterat composer?
`php composer.phar update` och `php composer.phar require walle89/swedbank-json` ger v0.7.1

**Comment by walle89** [comment]
Enligt Packagist så ska den vara [uppdaterad](https://packagist.org/packages/walle89/swedbank-json) och när jag nu kör en `require walle89/swedbank-json` så får jag 0.7.2. Normalt sätt behöver jag inte göra mer än att tagga releasen och pusha, vilket jag också gjort. Prova att rensa cachen med `php composer.phar clearcache` och uppdatera composer `php composer.phar self-update`, därefter testa att installera igen.

**Comment by NisseDILLIGAF** [comment]
Det fixa det... man lär sig något hela tiden :)
Tackar!

**Comment by CirruZZ** [comment]
Funkar! Tackar för snabb fix!
