### ISSUE TITLE
Uppdatera Appdata.json?

### ISSUE THREAD

**Issue by matthiaspalmer** [walle89/SwedbankJson#44]
Kan inte logga in längre, sen två dagar tillbaka krånglar det och efter att ha uppdaterat ordentligt till v1.0 och grävt runt lite ser jag felmeddelandet:

`{"errorMessages":{"general":[{"code":"AUTHORIZATION_FAILED","message":"Appen behöver uppdateras. Du har en äldre version av appen installerad på din telefon. För att komma vidare behöver du uppdatera till den senaste versionen."}]}}
`
Är det så att Swedbank har ändrat appen igen?

Visserligen hade jag inte uppdaterat till 1.0 tidigare, så jag trodde att det var det som var problemet först. Men efter att ha gjort uppgraderingen så får jag det ändå inte att fungera. Så om det fungerar för andra kanske det är jag som missar något i uppgraderingen.

/Matthias

**Comment by NisseDILLIGAF** [comment]
Hej

Såg att jag oxå får 'Appen behöver uppdateras'...
Har en gammal mobil jag har använt innan för att köra genom Charles för att plocka ut rätt AppID och useragent, men nu går det inte att köra Swedbank på den längre, för gammalt Android... (6.0.1) .. Swedbank vill att jag uppdaterar Android till en nyare version..
Ska se om jag kan få det att fungera med någon annan mobil, hittar jag något så postar jag här :)

**Comment by walle89** [comment]
Hejsan,

Sorry att jag inte har uppdaterat appdata på ett tag. Det har varit lite hektiskt ett tag med byte av jobb, osv. för min del. Hur som, jag har uppdaterat appdatan nu och det bör fungera för er från och med nu (förutsatt ni kör minst version 1.0 samt eventuellt har tömt er cache). Här är min commit med fixen: https://github.com/walle89/sbj-resources/commit/eaee01effb1d2bbd3e391749ba95c15e3d32284a

@matthiaspalmer Swedbank pensionerar deras äldre appar löpande vilket gör att man behöver uppdatera appdata i den takt som dem släpper uppdateringar av deras appar. För att komma åt appID och user agent så behöver man antingen avlyssna trafiken på ios eller en äldre version av Andoird, eller decompila Swedbank Android-appen och försöka antingen modifiera koden för att göra avlyssning möjligt eller försöka gräva fram informationen i samma kod.
