### ISSUE TITLE
Problem med SubscriptionID

### ISSUE THREAD

**Issue by adekvat-nu** [walle89/SwedbankJson#50]
Hej!

Jag försöker få SubscriptionID till ett av mina konton. Jag lyckas komma så långt att jag kan välja bland mina konton i dropdown-menyn, men när jag sen klickar vidare får jag inte ut något ID. Istället kastas jag tillbaka till autentisering/sign-in.

Skulle vara jättetacksam för hjälp!

**Comment by walle89** [comment]
Hur ser din kod ut?
